Repository dream-sports-labs/react-native-fast-image, pull requests merged in 2024-11, with the labels that each got.

#120 fix: added missing onLoad event details in android
  android/src/main/java/com/dylanvann/fastimage/FastImageRequestListener.java
  android/src/main/java/com/dylanvann/fastimage/events/FastImageLoadEvent.java
Labels: Impact: Bug, Platform: Android, Type: Both Architecture

#121 chore: updated readme with latest changes
  README.md
Labels: Type: Doc Changes

#136 feat: support webp animated image android
  android/build.gradle
  android/src/main/java/com/dylanvann/fastimage/FastImageViewWithUrl.java
Labels: First PR
